- name: be sure to get some facts about running instances
  local_action: ec2_remote_facts
    region="{{ ec2_region }}"
    filters="instance-id={{ ec2_id }}"
  register: result


- name: "be sure to set hostname for {{ result.instances[0].tags.Name }}"
  hostname:
    name: "{{ result.instances[0].tags.Name }}"


- name: be sure to add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: '127.0.1.1 {{ result.instances[0].tags.Name }}'
    regexp: '^127\.0\.1\.1'
    insertafter: '^127\.0\.0\.1'
    state: present



