- name: be sure ntp is installed
  apt: name=ntp state=present
  tags: ntp


- name: be sure ntp is configured
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify: restart ntp
  tags: ntp


- name: be sure NTP is running and enabled on boot.
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
