---
# tasks file for instance-facts
- name: be sure to get some facts about running instances
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:company": "{{ company }}"
  register: ec2_facts
  with_items: "{{ groups }}"


- name: be sure to set facts for instances
  set_fact: "{{ item.item }}_instances={{ item.instances }}"
  with_items: "{{ ec2_facts.results }}"


- name: be sure to set facts all instances
  set_fact: "ec2_all_instances={{ ec2_facts.results }}"


