---

galaxy_name: franklinkim.docker-compose
github_user: weareinteractive
github_name: ansible-docker-compose
badges: |
  [![Build Status](https://img.shields.io/travis/weareinteractive/ansible-docker-compose.svg)](https://travis-ci.org/weareinteractive/ansible-docker-compose)
  [![Galaxy](http://img.shields.io/badge/galaxy-franklinkim.docker-blue.svg)](https://galaxy.ansible.com/list#/roles/3275)
  [![GitHub Tags](https://img.shields.io/github/tag/weareinteractive/ansible-docker-compose.svg)](https://github.com/weareinteractive/ansible-docker-compose)
  [![GitHub Stars](https://img.shields.io/github/stars/weareinteractive/ansible-docker-compose.svg)](https://github.com/weareinteractive/ansible-docker-compose)
description: |
  > * installs docker-compose
after_dependencies: |
  * installed docker i.e. with [franklinkim.docker](https://github.com/weareinteractive/ansible-docker)
