---
# tasks file for instance
- name: be sure to create an instance
  ec2:
    instance_type: '{{ item.type }}'
    image: '{{ base_image }}'
    groups: '{{ item.security_groups }}'
    exact_count: '{{ item.count }}'
    key_name: '{{ aws_ssh_key_name }}'
    region: '{{ region }}'
    zone: '{{ zone }}'
    instance_tags:
      group: '{{ item.group }}'
      env: '{{ item.env }}'
    count_tag:
      group: '{{ item.group }}'
    wait: true
  with_items: '{{ instances }}'
  register: ec2_info


- name: be sure wait for instances to stand up (ssh)
  wait_for:
    host: '{{ item.public_dns_name }}'
    port: 22
    delay: 30
    timeout: 600
    state: started
  with_items: '{{ ec2_info.results.0.tagged_instances }}'




